<?php

// autoload_namespaces.php @generated by Composer

$vendorDir = dirname(dirname(__FILE__));
$baseDir = dirname($vendorDir);

return array(
    'Psr\\Log\\' => array($vendorDir . '/psr/log'),
    'DripFollowers\\' => array($baseDir . '/src'),
    'Carbon' => array($vendorDir . '/nesbot/carbon/src'),
);
